"""add_submission_graded_question_error_question

Revision ID: e6eae8925c17
Revises: 7af73b9909cc
Create Date: 2026-08-08 21:05:08.980834

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6eae8925c17'
down_revision: str | None = '7af73b9909cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Enum('english', 'math', name='subject_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='submission_status_enum'), nullable=False),
    sa.Column('original_image_path', sa.String(length=500), nullable=False),
    sa.Column('annotated_image_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('grading_raw_json', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_child_id', 'submissions', ['child_id'], unique=False)
    op.create_index('idx_submission_child_subject', 'submissions', ['child_id', 'subject'], unique=False)
    op.create_index('idx_submission_created_at', 'submissions', ['created_at'], unique=False)
    op.create_index('idx_submission_status', 'submissions', ['status'], unique=False)
    op.create_table('error_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Enum('english', 'math', name='error_subject_enum'), nullable=False),
    sa.Column('question_number', sa.String(length=20), nullable=False),
    sa.Column('question_type', sa.Enum('choice', 'fill_blank', 'reading', 'composition', 'calculation', 'word_problem', name='error_question_type_enum'), nullable=False),
    sa.Column('question_image_path', sa.String(length=500), nullable=False),
    sa.Column('solution_note', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('is_manually_fixed', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_timestamps', sa.JSON(), nullable=False),
    sa.Column('last_error_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_number', name='uq_eq_submission_question')
    )
    op.create_index('idx_eq_child_subject', 'error_questions', ['child_id', 'subject'], unique=False)
    op.create_index('idx_eq_child_type', 'error_questions', ['child_id', 'question_type'], unique=False)
    op.create_index('idx_eq_last_error', 'error_questions', ['last_error_at'], unique=False)
    op.create_table('graded_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(length=20), nullable=False),
    sa.Column('question_position', sa.JSON(), nullable=True),
    sa.Column('question_image_path', sa.String(length=500), nullable=True),
    sa.Column('question_type', sa.Enum('choice', 'fill_blank', 'reading', 'composition', 'calculation', 'word_problem', name='question_type_enum'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('solution_note', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('is_manually_fixed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gq_submission_correct', 'graded_questions', ['submission_id', 'is_correct'], unique=False)
    op.create_index('idx_gq_submission_id', 'graded_questions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gq_submission_id', table_name='graded_questions')
    op.drop_index('idx_gq_submission_correct', table_name='graded_questions')
    op.drop_table('graded_questions')
    op.drop_index('idx_eq_last_error', table_name='error_questions')
    op.drop_index('idx_eq_child_type', table_name='error_questions')
    op.drop_index('idx_eq_child_subject', table_name='error_questions')
    op.drop_table('error_questions')
    op.drop_index('idx_submission_status', table_name='submissions')
    op.drop_index('idx_submission_created_at', table_name='submissions')
    op.drop_index('idx_submission_child_subject', table_name='submissions')
    op.drop_index('idx_submission_child_id', table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
